apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 80
    targetPort: 80
  selector:
    name: ruby-webserver
      
